_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: aa8be65f-9fe8-40da-ac29-1e11c37d3f7b
name: Building-Blogsite
mail: akshay.dalvi@qed42.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
